// application/src/components/attempt-graph.tsx
"use client";

import type { TaskAttempt } from "../client/daemon-api.ts";
import { orderedAttempts, statePresentation } from "../client/daemon-ui-state.ts";

export function AttemptGraph({ attempts, branchId, selectedAttempt, onSelect }: { attempts: TaskAttempt[]; branchId?: string | null; selectedAttempt: string | null; onSelect: (attemptId: string | null) => void }) {
  const visible = orderedAttempts(attempts, branchId);
  return <ol className="attempt-graph" aria-label="Attempt lineage">{visible.map((attempt, index) => <li key={attempt.id} data-state={statePresentation(attempt.status)} data-selected={selectedAttempt === attempt.id}><button type="button" onClick={() => onSelect(selectedAttempt === attempt.id ? null : attempt.id)}><span aria-hidden="true">{index + 1}</span><strong>{attempt.name}</strong><small>Attempt {attempt.attempt ?? index + 1} · {attempt.status}{attempt.superseded ? " · superseded" : ""}</small></button></li>)}{!visible.length ? <li className="empty-state">No attempts yet.</li> : null}</ol>;
}

// web/src/components/AttemptGraph.vue
<script setup lang="ts">
import type { Phase } from "../types";

defineProps<{ phases: Phase[]; selectedId: string }>();
defineEmits<{ select: [id: string] }>();
</script>

<template>
  <div class="attempt-graph" aria-label="Task attempt graph">
    <button
      v-for="phase in phases"
      :key="phase.id"
      class="attempt-node"
      :class="{ selected: selectedId === phase.id }"
      :data-state="phase.status"
      type="button"
      @click="$emit('select', phase.id)"
    >
      <span>{{ phase.name }}</span>
      <small>#{{ phase.attempt || 1 }} · {{ phase.status }}</small>
    </button>
    <p v-if="phases.length === 0" class="rail-empty">Attempts appear here when the Task starts.</p>
  </div>
</template>
